baseURL = 'http://localhost:1313'
languageCode = 'en-us'
title = 'Computer Networking'
theme = "hugo-book"

[markup.tableOfContents]
  startLevel = 0
  
  
[params]
  BookTheme = 'auto'
  BookToC = true
  